ALTER TABLE customers ADD COLUMN IF NOT EXISTS employment_status VARCHAR(50);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS job_title VARCHAR(100);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS monthly_income VARCHAR(50);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS source_of_funds VARCHAR(100);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS kyc_status VARCHAR(50) DEFAULT 'ACTIVE';
