spring:
  # Tells Spring Boot to look one directory up (cd ..) for the .env file
  import: optional:file:../.env[.properties]
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:noreply@company.com}
    password: ${MAIL_PASSWORD:}
    default-sender: ${MAIL_FROM:noreply@company.com}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: true
            required: true
          ssl:
            trust: ${MAIL_HOST:smtp.gmail.com}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: hardened-banking-backend
  output:
    ansi:
      enabled: always
  main:
    allow-bean-definition-overriding: false

server:
  port: ${PORT:8080}
  address: 0.0.0.0  # <-- ADD THIS EXACT LINE
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
